# Generated by Django 4.2.1 on 2023-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_driver_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_image',
            field=models.CharField(),
        ),
    ]
