# Generated by Django 4.2.1 on 2023-05-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_driver_rating_alter_driver_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='date',
            field=models.CharField(),
        ),
    ]
