# Generated by Django 4.2.1 on 2023-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_image_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude_destination',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude_driver',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude_my_location',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude_destination',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude_driver',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude_my_location',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='rating_driver',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
