# Generated by Django 4.2.1 on 2023-05-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_latitude_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='latitude_destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitude_driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='latitude_my_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude_destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude_driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude_my_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='model_car',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_destination',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number_of_passengers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numbering_plate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rating_driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type_car',
        ),
        migrations.RemoveField(
            model_name='order',
            name='vehicle_image',
        ),
    ]
