# Generated by Django 4.2.1 on 2023-05-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_latitude_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_driver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profile_customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profile_driver',
        ),
    ]
