# Generated by Django 4.2.1 on 2023-05-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_id_driver_order_latitude_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image_payment',
            field=models.ImageField(null=True, upload_to='images/images_bay/'),
        ),
        migrations.AddField(
            model_name='order',
            name='offers',
            field=models.ManyToManyField(blank=True, to='orders.offer'),
        ),
    ]
