# Generated by Django 4.2.1 on 2023-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_image_payment_order_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='latitude_driver',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='longitude_driver',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='rating',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
